apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: my-web
spec:
  replicas: 3               # We want 3 pods
  selector:                 # This defines how the Deployment finds its Pods
    matchLabels:
      app: my-web
  # matchExpressions would go here for advanced filtering (Project 3)
  template:                 # This is the Pod Template
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: web-config